### ISSUE TITLE
Add SAT Chile maps to reference design simulation

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4mapbasedsims#6]
Documentation for the existing release is at:

https://github.com/CMB-S4/s4mapbasedsims/tree/master/202006_reference_design

the tool supports SAT Chile but I didn't run it because it is not in the reference design configuration.

@keskitalo @jdborrill how should I modify the instrument parameters?

Currently I have:

```toml
total_experiment_length_years = 7

# between 0 and 1, typically 0.2
observing_efficiency = 0.2

# Number of splits, 1 generates only full mission
# 2-7 generates the full mission map and then the requested number
# of splits scaled accordingly. E.g. 7 generates the full mission
# map and 7 equal (yearly) maps
number_of_splits = 7

[telescopes]

    # Telescope names are not used within the software

    [telescopes.SAT]
    # Available SAT tubes (band centers in GHz) are:
    # LFS (30,40), MFLS (85,145.1), MFHS (95,155.1), HFS (220,270)
    # Tubes for each SAT should be 3

    SAT1 = { LFS=0, MFLS= 3, MFHS=0, HFS=0, site="Pole", years=7 }
    SAT3 = { LFS=0, MFLS= 0, MFHS=3, HFS=0, site="Pole", years=7 }
    SAT5 = { LFS=1, MFLS= 0, MFHS=0, HFS=2, site="Pole", years=7 }

    SAT0 = { LFS=0, MFLS= 3, MFHS=0, HFS=0, site="Pole", years=7 }
    SAT2 = { LFS=0, MFLS= 0, MFHS=3, HFS=0, site="Pole", years=7 }
    SAT4 = { LFS=1, MFLS= 0, MFHS=0, HFS=2, site="Pole", years=7 }
```
